[WIP] Generalize momentum-conserving interpolation functions for MR
ECP-WarpX/WarpX pull request #1650
Opened 2021-01-23 00:42 UTC by EZoni

This PR generalizes, with respect to the refinement ratio, the interpolation functions called within `WarpX::UpdateAuxilaryDataStagToNodal` to interpolate data from the coarse and fine grids to the fine `aux` grid, with momentum-conserving field gathering (hence between grids with different staggerings).

The new function `warpx_interp` (overload) replaces the following old functions:
- `warpx_interp_nd_bfield_x`
- `warpx_interp_nd_bfield_y`
- `warpx_interp_nd_bfield_z`
- `warpx_interp_nd_efield_x`
- `warpx_interp_nd_efield_y`
- `warpx_interp_nd_efield_z`

The case of refinement ratio = 2, in 2D, is recovered, as the CI test `momentum-conserving-gather` confirms.

However, I suggest that we merge this PR only after we will have a CI test dedicated to MR with refinement ratio > 2 (possibly both 2D and 3D), which will test the new functions implemented both in #1585 (already merged) and here.

2022-01-31 23:37 UTC, EZoni commented
The zero padding added as a part of this PR fixes the out-of-bound array access occurring, for instance, with the CI test `Langmuir_multi_2d_MR` when one sets `algo.field_gathering = momentum-conserving` and runs in DEBUG mode.

2023-10-04 16:00 UTC, RemiLehe commented on Source/Parallelization/WarpXComm_K.H
>  AMREX_GPU_DEVICE AMREX_FORCE_INLINE
Could add a quick docstring to this function (as well as the `warpx_interp` function above that has the same name but a different signature), in order to explain the difference between these two functions. Also: in the doctring, could you specify whether `arr_fine_stag` applies to `arr_fine` or `arr_aux` (same comment for `arr_stag` in the above function `warpx_interp` of the same name).

2023-10-04 16:01 UTC, RemiLehe commented on Source/Parallelization/WarpXComm_K.H
> +    const     int sk_fp = arr_fine_stag[1];
```suggestion
    const int sk_fp = arr_fine_stag[1];
```

2023-10-04 16:34 UTC, RemiLehe requested changes
Thanks for this PR. Could you add some docstrings, as mentioned in inline comments?

2023-10-04 18:34 UTC, RemiLehe approved these changes
Thanks again. I added one more small request, and then this should be good to go.

2023-10-04 18:34 UTC, RemiLehe commented on Source/Parallelization/WarpXComm_K.H
> + * with momentum-conserving field gathering, hence between grids with different staggering.
Thanks for updating the docstring. Could you add one more sentence, indicating explicitly that the staggering of the `aux` grid is assumed to be nodal.

2023-10-04 18:40 UTC, EZoni commented on Source/Parallelization/WarpXComm_K.H
> + * with momentum-conserving field gathering, hence between grids with different staggering.
Yes, thank you for the reminder. Done in [7b676d6](https://github.com/ECP-WarpX/WarpX/pull/1650/commits/7b676d6f525208dc496499d9987768838e03f88d).

2023-10-04 19:48 UTC, RemiLehe approved these changes

2023-10-04 20:54 UTC, EZoni commented
Needs to be rebased once #4341 is merged, in order to fix the macOS/AppleClang check.

2023-10-05 01:39 UTC, merged