Add a delay to laser profile read from "txye" file
ECP-WarpX/WarpX pull request #1816
Opened 2021-03-19 11:28 UTC by lucafedeli88

This PR allows delaying or anticipating a laser read from a "txye" file

2021-03-29 17:32 UTC, RemiLehe requested changes
Thanks for this PR! I have a two small typographic corrections.

2021-03-29 17:32 UTC, RemiLehe commented on Docs/source/running_cpp/parameters.rst
> +      setting the additional parameter ``<laser_name>.txye_file_name`` (``string`). It accepts an
```suggestion
      setting the additional parameter ``<laser_name>.txye_file_name`` (`string`). It accepts an
```

2021-03-29 17:32 UTC, RemiLehe commented on Docs/source/running_cpp/parameters.rst
> +      delaying (``delay`` > 0) or anticipating (``delay < 0``) the laser by the specified amount of time.
```suggestion
      delaying (``delay > 0``) or anticipating (``delay < 0``) the laser by the specified amount of time.
```

2021-04-05 20:10 UTC, RemiLehe commented
@lucafedeli88 There seems to be a merge conflict. Would you have time to resolve it?

2021-04-07 00:53 UTC, lucafedeli88 commented
> @lucafedeli88 There seems to be a merge conflict. Would you have time to resolve it?

It should be OK now...

2021-04-12 22:06 UTC, RemiLehe approved these changes

2021-04-12 22:06 UTC, merged