Interface silver mueller
ECP-WarpX/WarpX pull request #2051
Opened 2021-07-02 20:28 UTC by RevathiJambunathan

2021-07-12 19:01 UTC, RemiLehe requested changes
Thanks a lot for this PR! I have a few minor requests.

2021-07-12 19:01 UTC, RemiLehe commented on Source/Evolve/WarpXEvolve.cpp
> +        //if (do_silver_mueller) ApplySilverMuellerBoundary( dt[0] );
Minor clean-up
```suggestion
```

2021-07-12 19:01 UTC, RemiLehe commented on Source/FieldSolver/WarpXPushFieldsEM.cpp
> +//}
Minor cleanup
```suggestion
```

2021-07-12 19:01 UTC, RemiLehe commented on Source/BoundaryConditions/WarpXFieldBoundaries.cpp
> +
Could you add a comment:
```suggestion

    // Silver-Mueller boundaries are only applied on the first half-push of B
    // This is because the formula used for Silver-Mueller assumes that 
    // E and B are staggered in time, which is only true after the first half-push
```

2021-07-12 19:01 UTC, RemiLehe commented on Source/BoundaryConditions/WarpXFieldBoundaries.cpp
> +            }
Could this be replaced by a dedicated function `isAnyBoundarySilverMueller` (similarly to `isAnyBoundaryPEC`)?

2021-07-12 19:06 UTC, RevathiJambunathan commented on Examples/Tests/SilverMueller/inputs_2d_z
> +#geometry.is_periodic = 0   0   0
```suggestion
```

2021-07-12 19:06 UTC, RevathiJambunathan commented on Examples/Tests/SilverMueller/inputs_2d_x
> +#geometry.is_periodic = 0   0   0
```suggestion
```

2021-07-12 19:06 UTC, RevathiJambunathan commented on Examples/Tests/SilverMueller/inputs_rz_z
> +#geometry.is_periodic = 0   0   0
```suggestion
```

2021-07-12 19:07 UTC, RevathiJambunathan commented on Source/BoundaryConditions/WarpXFieldBoundaries.cpp
> +            }
yes definitely! Thank you

2021-07-12 19:38 UTC, RevathiJambunathan commented on Source/Utils/WarpXUtil.cpp
> +                , " The current implementation requires silver-mueller boundary condition to be applied at all boundaries!");
@RemiLehe I added a temporary abort statement here ensuring that silver-mueller is selected on all valid boundaries if selected for one -- such that it is aligned with the current implementation

2021-07-13 07:27 UTC, RemiLehe approved these changes

2021-07-13 07:27 UTC, merged