Add option to specificy absolute tolerance for the MLMG solver
ECP-WarpX/WarpX pull request #2410
Opened 2021-10-12 19:44 UTC by roelof-groenewald

In simulations where the charge density changes very little from step to step, the MLMG solver has been seen to fail to converge since the initial guess for `phi` (from the solution of the previous step) is so close to the "correct" solution that it cannot sufficiently be improved to satisfy the `required_precision` value. In cases such as this it is useful to also specify an absolute tolerance for convergence of the field solution. This PR adds the ability to pass an absolute tolerance to the MLMG solver.

Additionally, a suggested improvement is made for electrostatic simulations: Given a linear system `Ax = b` with initial solution guess, `x_0`, the AMReX MLMG solver uses `max_norm = max(|(b - Ax_0)|, |b|)` (where `|.|` indicate max-norm) to evaluate relative convergence at each iteration step (by evaluating `required_precision < |(b - Ax)| / max_norm`). This only really checks the solution convergence if `max_norm = |b|`, which can be forced with setting `always_use_bnorm = True` for the MLMG solver. In this PR `ElectrostaticSolver.cpp` has been edited to force the MLMG solver to use `|b|` unless `|b| == 0`, in which case it adds an absolute tolerance criteria of `1e-6` V/m^2 if no absolute tolerance is specified (this is to avoid the problem described in the first paragraph).

2021-10-25 21:42 UTC, RemiLehe requested changes

2021-10-25 21:42 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +    if (!always_use_bnorm) {
Could you use the new warning logger from [this PR](https://github.com/ECP-WarpX/WarpX/pull/2113) here?

2021-10-25 21:42 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +    if (!always_use_bnorm) {
Could you use the new warning logger from [this PR](https://github.com/ECP-WarpX/WarpX/pull/2113) here?

2021-10-25 21:42 UTC, RemiLehe commented on Docs/source/usage/parameters.rst
> +    the MLMG solver is so close to the converged value that is fails to improve
```suggestion
    the MLMG solver is so close to the converged value that it fails to improve
```

2021-10-25 21:42 UTC, RemiLehe commented on Docs/source/usage/parameters.rst
> +    value.
Could you state here again that this only used if the charge density is zero?

2021-10-25 21:42 UTC, RemiLehe commented on Docs/source/usage/parameters.rst
> +    value.
Could you state here again that this only used if the charge density of this species is zero?

2021-10-25 21:42 UTC, RemiLehe requested changes

2021-10-25 21:42 UTC, RemiLehe commented on Docs/source/usage/parameters.rst
> +    the MLMG solver is so close to the converged value that is fails to improve
```suggestion
    the MLMG solver is so close to the converged value that it fails to improve
```

2021-10-25 22:56 UTC, roelof-groenewald commented on Docs/source/usage/parameters.rst
> +    value.
If a value is specified for `self_fields_required_precision` in the input file it will be used regardless of whether or not `rho` is zero. In the case that a value is not specified it will by default be 0, unless `rho` is zero in which case the default value changes to 1e-6 V/m^2. Would you like me to change the logic so that an absolute error tolerance other than 0 will be used if and only if `|rho| == 0`?

2021-10-26 04:53 UTC, RemiLehe commented on Docs/source/usage/parameters.rst
> +    value.
OK, thanks for clarifying :)

2021-10-26 05:24 UTC, roelof-groenewald commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +    if (!always_use_bnorm) {
No problem, I switched the print statements over to use the warning logger instead.

2021-10-29 20:26 UTC, RemiLehe approved these changes

2021-10-29 20:26 UTC, merged