Bugfix in load balancing routine
ECP-WarpX/WarpX pull request #2555
Opened 2021-11-12 20:34 UTC by roelof-groenewald

Add remake of phi_fp during load balancing RemakeLevel

2021-11-12 21:25 UTC, PhilMiller commented
Modification looks good to me. But wow, is that function screaming to have a helper defined!

2021-11-12 23:10 UTC, ax3l commented
X-Ref: Follow-up to #1531

2021-11-12 23:12 UTC, ax3l approved these changes
Thanks a lot!

Will assign an extra set of eyes.

2021-11-12 23:20 UTC, dpgrote approved these changes
Good catch. This looks good to me

2021-11-13 16:41 UTC, RemiLehe requested changes, later dismissed
Thanks for this PR! Could you do the same change for `phi_cp` (This would be used for mesh refinement.)

2021-11-13 16:41 UTC, RemiLehe commented on Source/Parallelization/WarpXRegrid.cpp
> +        }
Could you also add `phi_cp` further below?

2021-11-14 21:10 UTC, roelof-groenewald commented on Source/Parallelization/WarpXRegrid.cpp
> +        }
No problem.

2021-11-14 22:18 UTC, roelof-groenewald commented on Source/Parallelization/WarpXRegrid.cpp
> +        }
Actually it doesn't look like `phi_cp` is defined anywhere.

2021-11-15 19:21 UTC, merged

2021-11-15 19:23 UTC, RemiLehe commented on Source/Parallelization/WarpXRegrid.cpp
> +        }
Ah, yes, that's right. I got confused.