Correct fusion algorithm in RZ
ECP-WarpX/WarpX pull request #2569
Opened 2021-11-16 20:53 UTC by Yin-YinjianZhao

This PR mimics the one in PR #2510 to correct the fusion algorithm in RZ.

2021-11-16 21:15 UTC, RemiLehe commented
@NeilZaim I have added you as a reviewer here, but we could discuss in more detail why this rotation is needed, during the next developer meeting (next Tuesday).
Also: I think that we could discuss whether the second part of the fusion algorithm (the creation of particles with the correct momenta, as implemented in https://github.com/ECP-WarpX/WarpX/pull/2330) is already valid for RZ.

2021-11-16 21:33 UTC, RemiLehe requested changes

2021-11-16 21:33 UTC, RemiLehe commented on Source/Particles/Collision/BinaryCollision/NuclearFusionFunc.H
> +          amrex::ParticleReal const u1xbuf_new = u1x[I1[i1]];
@Yin-YinjianZhao Could you re-indent this part of the code, so that it agrees with the rest of the code?

2021-11-18 13:16 UTC, NeilZaim approved these changes
Hello. Yes, this change sounds reasonable to me if we have a perfect axial symmetry (order 0 RZ). I don't know if modifying the momenta to machine precision is an issue (I guess not) but if we want to avoid that then it's easy to do.

Also, yes we would need to do something similar for the initialization of the product particles (rotate the momentum of one of the colliding particles before and rotate back the momentum of half the produced particles after). I can do that in a follow-up to #2330 if needed.

2022-09-19 16:59 UTC, closed without merging

2022-09-19 17:00 UTC, RemiLehe commented
This is superseded by #3255