Add mesh refinement for electrostatic solver
ECP-WarpX/WarpX pull request #2728
Opened 2022-01-07 18:02 UTC by Yin-YinjianZhao

2022-01-11 01:23 UTC, RemiLehe requested changes
Thanks for starting to work on this. 
I suggested a few changes ; could you include them in this PR?

2022-01-11 01:23 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +            MultiFab dphi(phi_cp.boxArray(), phi_cp.DistributionMap(), phi_cp.nComp(), ng);
```suggestion
```

2022-01-11 01:23 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +                //Array4<Real const> const& phi_c = dphi.const_array(mfi);
```suggestion
```

2022-01-11 01:23 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +            BoxArray ba = phi_cp.boxArray();
```suggestion
            BoxArray ba = phi[lev+1]->boxArray();
```

2022-01-11 01:23 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +            const IntVect& refratio = refRatio(lev-1);
```suggestion
            const IntVect& refratio = refRatio(lev);
```

2022-01-11 01:23 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +            MultiFab cfine(ba, phi_cp.DistributionMap(), ncomp, ng_dst);
```suggestion
            MultiFab cfine(ba, phi[lev+1]->DistributionMap(), ncomp, 1);
```

2022-01-11 01:23 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +            WarpXCommUtil::ParallelCopy(phi_cp, *phi[lev], 0, 0, 1, ng_src, ng, crse_period);
```suggestion
            const amrex::Periodicity& crse_period = Geom(lev).periodicity();
            WarpXCommUtil::ParallelCopy(phi_cp, *phi[lev], 0, 0, 1, 1, 1, crse_period);
```

2022-01-11 01:23 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +                Array4<Real> const& phi_aux = phi[lev]->array(mfi);
```suggestion
```

2022-01-11 01:23 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +                //});
```suggestion
                amrex::ParallelFor(Box(phi_aux),
                [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept
                {
                    mf_nodebilin_interp(i, j, k, 0, phi_fp_arr, 0, phi_cp_arr, 0, refratio);
                });
```

2022-01-11 01:23 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +                //});
See this for more info:
https://amrex-codes.github.io/amrex/doxygen/namespaceamrex.html#ab0fde5a29bb528390db2710d71ea4825
Note that you will need to include `AMReX_MFInterp_C.H` at the top of this file, in order for `mf_nodebilin_interp` to be available.

2022-01-11 20:59 UTC, RemiLehe requested changes

2022-01-11 20:59 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +            MultiFab cfine(ba, phi[lev+1]->DistributionMap(), ncomp, 1);
```suggestion
            MultiFab phi_cp(ba, phi[lev+1]->DistributionMap(), ncomp, 1);
```

2022-01-11 20:59 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +                Array4<Real const> const& phi_fp = phi[lev]->const_array(mfi);
```suggestion
                Array4<Real const> const& phi_fp_arr = phi[lev]->array(mfi);
                Array4<Real const> const& phi_cp_arr = phi_cp->array(mfi);                
```

2022-01-13 20:21 UTC, RemiLehe requested changes

2022-01-13 20:21 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +            for (MFIter mfi(*phi[lev]); mfi.isValid(); ++mfi)
```suggestion
            for (MFIter mfi(*phi[lev+1],TilingIfNotGPU()); mfi.isValid(); ++mfi)
```

2022-01-13 20:21 UTC, RemiLehe commented on Source/FieldSolver/ElectrostaticSolver.cpp
> +                amrex::ParallelFor(Box(phi[lev]->array(mfi)),
```suggestion
                Box const& b = mfi.tilebox(phi[lev+1]->ixType().toIntVect());
                amrex::ParallelFor( b,
```

2022-01-26 17:40 UTC, Yin-YinjianZhao commented
Right now, the PR can compile but has runtime errors as follows.
@RemiLehe and I couldn't figure out why, so we need help maybe from @WeiqunZhang and @atmyers.

1) A test in RZ with embedded BC and mesh refinement, based on `Examples/Tests/ElectrostaticSphereEB/inputs_rz`.
I compiled using `make -j 4 USE_RZ=TRUE USE_EB=TRUE DEBUG=TRUE`.
The input is [inputs_rz.txt](https://github.com/ECP-WarpX/WarpX/files/7943865/inputs_rz.txt).
The output is [outputs_rz.txt](https://github.com/ECP-WarpX/WarpX/files/7943868/outputs_rz.txt).
The Backtrace is [Backtrace_rz.txt](https://github.com/ECP-WarpX/WarpX/files/7943872/Backtrace_rz.txt)
In short, we obtained an out-of-bound error:
```
amrex::Abort::0:: (-1,10,0,0) is out of bound (-1:37,11:52,0:0,0:0) !!!
SIGABRT
```

2) A test in RZ with embedded BC and mesh refinement testing particle scarping, based on `Examples/Tests/scraping/inputs_rz`.
I compiled using `make -j 4 USE_RZ=TRUE USE_EB=TRUE DEBUG=TRUE`.
The input is [inputs_rz_scraping.txt](https://github.com/ECP-WarpX/WarpX/files/7943900/inputs_rz_scraping.txt).
The output is [outputs_rz_scraping.txt](https://github.com/ECP-WarpX/WarpX/files/7943902/outputs_rz_scraping.txt).
The Backtrace is [Backtrace_rz_scraping.txt](https://github.com/ECP-WarpX/WarpX/files/7943907/Backtrace_rz_scraping.txt).
In short, again we got this error:
```
amrex::Abort::amrex::Abort::0:: (-1,59,0,0) is out of bound (0:36,60:64,0:0,0:0) !!!
0:: (-1,-1,0,0) is out of bound (0:36,0:36,0:0,0:0) !!!
SIGABRT
```

3) A test in 3D with mesh refinement, based on `Examples/Tests/ElectrostaticSphere/inputs_3d`.
I compiled using `make -j 4 DEBUG=TRUE`.
The input is [inputs_3d.txt](https://github.com/ECP-WarpX/WarpX/files/7943922/inputs_3d.txt).
The output is [outputs_3d.txt](https://github.com/ECP-WarpX/WarpX/files/7943925/outputs_3d.txt).
The Backtrace is [Backtrace_3d.txt](https://github.com/ECP-WarpX/WarpX/files/7943926/Backtrace_3d.txt).
The error reads:
```
amrex::Abort::0:: (15,15,24,0) is out of bound (16:48,16:48,16:48,0:0) !!!
SIGABRT
amrex::Abort::0:: (15,15,40,0) is out of bound (16:48,16:48,16:48,0:0) !!!
amrex::Abort::0:: (15,15,32,0) is out of bound (16:48,16:48,16:48,0:0) !!!
amrex::Abort::0:: (15,15,15,0) is out of bound (16:48,16:48,16:48,0:0) !!!
```

2022-01-26 20:24 UTC, RemiLehe commented
I think that the error in 1) probably comes from this line: 
https://github.com/ECP-WarpX/WarpX/blob/development/Source/Parallelization/WarpXComm_K.H#L115
We probably need some drawing of the interpolation operation in order to understand why this is happening.

2022-01-31 18:12 UTC, RemiLehe commented
After discussing with @EZoni , it seems that the above issues maybe independent from this PR.

While we confirm this, coud you finalize this PR? In particular, I think that the new tests require the corresponding benchmark to be set. (see https://warpx.readthedocs.io/en/latest/developers/checksum.html#reset-a-benchmark-from-a-plotfile-you-know-is-correct)

2022-01-31 18:13 UTC, RemiLehe commented
Also: it seems that the `ElectrostaticSphereRZ` failed to compile...

2022-02-01 23:01 UTC, EZoni commented
I'll jump in with a question, triggered by another issue I was looking at recently. Do the boundary conditions defined in `ElectrostaticSolver::BoundaryHandler::definePhiBCs` need to be updated for more than one mesh refinement level as well?

2022-02-16 21:39 UTC, RemiLehe commented
Regarding the problem #3: my impression is that is that it also occurs on the `development` branch (The traceback points to [this line](https://github.com/ECP-WarpX/WarpX/blob/development/Source/Particles/WarpXParticleContainer.cpp#L726)). This should be reported as a separate issue. But for now, it can be ignored for this PR.

2022-02-17 19:46 UTC, Yin-YinjianZhao commented
After the above merge, the test 3 mentioned here (https://github.com/ECP-WarpX/WarpX/pull/2728#issuecomment-1022434816) can run without any issues.

Test 2 still got an error. The output and the backtrace files are attached.

[Backtrace_rz_scraping2.txt](https://github.com/ECP-WarpX/WarpX/files/8091719/Backtrace_rz_scraping2.txt)
[outputs_rz_scraping2.txt](https://github.com/ECP-WarpX/WarpX/files/8091720/outputs_rz_scraping2.txt)

2022-02-17 20:16 UTC, RemiLehe commented on Source/WarpX.cpp
>  #ifdef AMREX_USE_EB
```suggestion
#ifdef AMREX_USE_EB
    constexpr int nc_ls = 1;
    constexpr int ng_ls = 2;
    m_distance_to_eb[lev] = std::make_unique<MultiFab>(amrex::convert(ba, IntVect::TheNodeVector()), dm, nc_ls, ng_ls, tag("m_distance_to_eb"));

```

2022-02-17 22:15 UTC, RemiLehe approved these changes

2022-02-22 18:03 UTC, Yin-YinjianZhao commented
Right now, it is found that the modified `Examples/Tests/scraping` test cannot pass after adding mesh refinement.
We found that the particles cannot be removed as desired and behave weird.
![rz](https://user-images.githubusercontent.com/56095356/155191327-188fcd94-8f03-4e52-ae28-9789256e1ee4.gif)
Without mesh refinement, the original scraping test gives:
![rz](https://user-images.githubusercontent.com/56095356/155191428-9ab3bc74-4acc-4fda-9255-13090c659ef8.gif)
Plotting the average `vx` of all particles over time:
<img width="612" alt="Screen Shot 2022-02-22 at 11 01 42 AM" src="https://user-images.githubusercontent.com/56095356/155191989-dff37256-08a4-4b7b-ad08-077621f5ea49.png">
So, it seems like the initial velocities are correct.
@RemiLehe Any other things I should plot and check?

2022-02-22 23:28 UTC, RemiLehe commented
It looks like, for some particles, the `x` and `y` position jumps after the first iteration (but in a way that preserve the radius `r`). Here is for instance a plot where I tracked the `x`, `y` and `r` position of a particle.

![Screen Shot 2022-02-22 at 3 25 04 PM](https://user-images.githubusercontent.com/6685781/155236734-7012c81a-cba0-4dcf-8e12-de6c724e7d5b.png)

This suggests that maybe the `theta` information is not properly copied: https://github.com/ECP-WarpX/WarpX/blob/development/Source/Particles/WarpXParticleContainer.H#L53

(As a side note, here is the code that was used to produce the plot - see [this tutorial](https://github.com/openPMD/openPMD-viewer/blob/dev/tutorials/4_Particle_selection.ipynb) for more info:
```
from openpmd_viewer import OpenPMDTimeSeries
from openpmd_viewer import ParticleTracker
import matplotlib.pyplot as plt
ts = OpenPMDTimeSeries('./diags/diag1/')
pt = ParticleTracker( ts, iteration=37, select={'z':[400e-3,450e-3]},  preserve_particle_index=True )
x, y, z = ts.iterate( ts.get_particle, ['x', 'y', 'z'], select=pt )

# index of the particle to look at
i = 100
plt.plot( ts.iterations, x[:,i], '-o', label='x');
plt.plot( ts.iterations, y[:,i], '-o', label='y');
plt.plot( ts.iterations, (x[:,i]**2 + y[:,i]**2)**.5, '-o', label='r');
plt.legend(loc=0)
plt.xlabel('Iteration')
```

2022-02-22 23:38 UTC, RemiLehe commented
Btw, @Yin-YinjianZhao are you able to tell where the mesh refinement patches are located?
(You could e.g. plot them with `yt.annotate_grids()`.)

2022-02-22 23:56 UTC, RemiLehe commented
@Yin-YinjianZhao Here are a few other things that @atmyers suggested to try:
- Could you try to run this case with a version of WarpX compiled *without EB*. In this case, the particles would of course not be removed at `r=0.1`, but it would be interesting to see whether we see the same problems in the first few iterations (i.e. some particles going in the wrong direction)
- Could you also try to run with `warpx.n_field_gather_buffer = 0` and `warpx.n_current_deposition_buffer = 0` in the input script, and see whether that fixes the issue?

2022-02-23 01:00 UTC, RemiLehe commented
It seems that the bug comes from the fact that we are not sorting the angle theta of the particles here:
https://github.com/ECP-WarpX/WarpX/blob/development/Source/Particles/Sorting/Partition.cpp#L151

2022-02-23 04:45 UTC, RemiLehe commented on Regression/WarpX-tests.ini
> +runtime_params =
```suggestion
runtime_params =  warpx.abort_on_warning_threshold = medium
```

2022-02-23 04:51 UTC, RemiLehe commented
@Yin-YinjianZhao I attempted to fix the issue with [this commit](https://github.com/ECP-WarpX/WarpX/pull/2728/commits/562f1fbe1b81ede02713e9566aa1307751465384) above.
Could you re-compile and produce again the above small movie (with mesh refinement)?

2022-02-23 17:27 UTC, Yin-YinjianZhao commented
@RemiLehe After your fix, I got this:
![zr](https://user-images.githubusercontent.com/56095356/155373435-478f980e-f727-4a65-990d-d449724916fc.gif)
![rv](https://user-images.githubusercontent.com/56095356/155373540-bdd0812e-d79e-4760-bdab-c6676d822b2d.gif)

2022-02-24 01:29 UTC, merged