ABLASTR: Move TextMsg
ECP-WarpX/WarpX pull request #2953
Opened 2022-03-10 00:22 UTC by ax3l

Since this is used in a ABLASTR header, we need to compile this in ABLASTR, so ImpactX can use it as well. Otherwise we have missing symbols for that utility.

Follow-up to #2939

2022-03-10 09:55 UTC, lucafedeli88 approved these changes
Thanks Axel!

2022-03-10 09:57 UTC, lucafedeli88 requested changes, later dismissed
There is a small typo, otherwise looks fine to me!

2022-03-10 09:57 UTC, lucafedeli88 commented on Source/ablastr/utils/Make.package
> +CEXE_sources += TestMsg.cpp
```suggestion
CEXE_sources += TextMsg.cpp
```

2022-03-10 20:10 UTC, ax3l commented on Source/ablastr/utils/Make.package
> +CEXE_sources += TestMsg.cpp
Thanks, that explains why CI fails :D

2022-03-10 22:49 UTC, ax3l reviewed
Apply exact wording from  #2946

2022-03-10 22:49 UTC, ax3l commented on Source/ablastr/utils/TextMsg.H
> +    * @param[in] do_text_wrapping if true, the message is automatically wrapped
```suggestion
    * @param[in] do_text_wrapping if true, the text of the message is automatically wrapped
```

2022-03-10 22:49 UTC, ax3l commented on Source/ablastr/utils/TextMsg.H
> +    * @param[in] do_text_wrapping if true, the message is automatically wrapped
```suggestion
    * @param[in] do_text_wrapping if true, the text of the message is automatically wrapped
```

2022-03-10 22:49 UTC, ax3l commented on Source/ablastr/utils/TextMsg.H
> +    * @param[in] do_text_wrapping if true, the message is automatically wrapped
```suggestion
    * @param[in] do_text_wrapping if true, the text of the message is automatically wrapped
```

2022-03-10 22:57 UTC, ax3l commented
@lucafedeli88 ready for re-approval :)

2022-03-11 16:52 UTC, lucafedeli88 approved these changes
Thanks for this PR @ax3l !

2022-03-11 16:52 UTC, merged