Extract fusion for two-particle fusion reaction
ECP-WarpX/WarpX pull request #3175
Opened 2022-06-10 18:18 UTC by RemiLehe

This PR refactors the p-B fusion code by extracting a function for the first part of the reaction (p+B -> Be+alpha). 

This part is made a separate function that can calculate the momenta of the products in any two-product reaction (X1 + X2 -> Y1+Y2), based on the conservation of energy and momentum. This will be useful in other fusion reaction (e.g. #3153 )

2022-06-15 14:31 UTC, NeilZaim approved these changes
Thanks for this PR, it looks good to me!

I've only left some suggestions fixing some comments. And you can also remove the comment on line 67 of `ProtonBoronFusionInitializeMomentum.H` :
```
// x_star denotes the value of x in the proton+boron center of mass frame
```
since I no longer see a variable of the form `x_star`.

2022-06-15 14:31 UTC, NeilZaim commented on Source/Particles/Collision/BinaryCollision/NuclearFusion/TwoProductFusionUtil.H
> +     * @param[in] m2_out mass of the first product macroparticles
```suggestion
     * @param[in] m2_out mass of the second product macroparticles
```

2022-06-15 14:31 UTC, NeilZaim commented on Source/Particles/Collision/BinaryCollision/NuclearFusion/TwoProductFusionUtil.H
> +     * @param[in] engine the random engine (used to calculate the angle of emission of the productss)
```suggestion
     * @param[in] engine the random engine (used to calculate the angle of emission of the products)
```

2022-06-15 14:31 UTC, NeilZaim commented on Source/Particles/Collision/BinaryCollision/NuclearFusion/TwoProductFusionUtil.H
> +        // Convert momentum of first alpha to lab frame, using equation (13) of F. Perez et al.,
```suggestion
        // Convert momentum of first product to lab frame, using equation (13) of F. Perez et al.,
```

2022-06-15 14:42 UTC, RemiLehe commented
Thanks a lot for your review. I applied the requested changes.

2022-06-15 16:15 UTC, EZoni requested changes
Thank you for this PR, @RemiLehe! I just left one comment, I think there's a couple of typos in the Doxygen strings for the new function. Other than this, it looks good to me and can be merged as soon as it's ready.

2022-06-15 16:15 UTC, EZoni commented on Source/Particles/Collision/BinaryCollision/NuclearFusion/TwoProductFusionUtil.H
> +     * @param[in] m2_out mass of the second product macroparticles
```suggestion
     * @param[in] u1x_in normalized momentum of the first colliding macroparticles along x (in m.s^-1)
     * @param[in] u1y_in normalized momentum of the first colliding macroparticles along y (in m.s^-1)
     * @param[in] u1z_in normalized momentum of the first colliding macroparticles along z (in m.s^-1)
     * @param[in] m1_in mass of the first colliding macroparticles
     * @param[in] u2x_in normalized momentum of the second colliding macroparticles along x (in m.s^-1)
     * @param[in] u2y_in normalized momentum of the second colliding macroparticles along y (in m.s^-1)
     * @param[in] u2z_in normalized momentum of the second colliding macroparticles along z (in m.s^-1)
     * @param[in] m2_in mass of the second colliding macroparticles
     * @param[out] u1x_out normalized momentum of the first product macroparticles along x (in m.s^-1)
     * @param[out] u1y_out normalized momentum of the first product macroparticles along y (in m.s^-1)
     * @param[out] u1z_out normalized momentum of the first product macroparticles along z (in m.s^-1)
     * @param[in] m1_out mass of the first product macroparticles
     * @param[out] u2x_out normalized momentum of the second product macroparticles along x (in m.s^-1)
     * @param[out] u2y_out normalized momentum of the second product macroparticles along y (in m.s^-1)
     * @param[out] u2z_out normalized momentum of the second product macroparticles along z (in m.s^-1)
     * @param[in] m2_out mass of the second product macroparticles
```

2022-06-16 15:52 UTC, EZoni approved these changes

2022-06-16 15:52 UTC, merged