[WIP] Fix a bug for Intra-species Coulomb collisions
ECP-WarpX/WarpX pull request #3526
Opened 2022-11-15 20:03 UTC by Yin-YinjianZhao

For inner species collisions, there is a bug of calculating the number density.
This PR aims to fix this bug.

2022-11-15 20:36 UTC, RemiLehe commented on Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
> +        n1 = n1 / dV; n2 = n1; n12 = n1;
I agree with the calculation of `n1` and `n2` here, but I think that the calculation of `n12` is too simple (i.e. only valid in the case where all weights are equal). I think that we should instead use the same code that calculates `n12` below.

2022-11-15 20:37 UTC, RemiLehe commented on Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
> +        for (int i1=I1s; i1<static_cast<int>(I1e); ++i1) { n1 += w1[ I1[i1] ]; }
It seems that the calculation of `n2` is missing here...

2022-11-15 20:39 UTC, RemiLehe commented on Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
> +        }
I think that this should be outside of the `else` statement, as it also applies for intraspecies.
The only thing is that we would need to add these additional lines at the end, in order to match formula 38 from the Higginson paper:
```
if (isSameSpecies) {
    n12 *= 2;
}
```

2022-11-18 22:46 UTC, EZoni commented on Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
>      }
Seems like the temporary declarations of `i1` and `i2` inside the `for` loops shadow previous local declarations of the same variables (line 86 above). The CI builds treat all warnings as errors and thus fail.

2022-11-23 14:20 UTC, RemiLehe commented on Regression/WarpX-tests.ini
> +compareParticles = 0
```suggestion
compareParticles = 1
```

2022-11-23 16:35 UTC, RemiLehe commented on Examples/Tests/collision/analysis_collision_3d_isotropization.py
> +checksumAPI.evaluate_checksum(test_name, fn, do_particles=False)
```suggestion
checksumAPI.evaluate_checksum(test_name, fn)
```

2022-11-24 15:47 UTC, RemiLehe commented on Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
> +        n1 = n1 / dV; n2 = n2 / dV;
```suggestion
    for (int i1=I1s; i1<static_cast<int>(I1e); ++i1 ) { n1 += w1[ I1[i1] ]; }
    for (int i2=I2s; i2<static_cast<int>(I2e); ++i2 ) { n1 += w2[ I2[i2] ]; }
    n1 = n1 / dV; n2 = n1;
    if ( isSameSpecies ) {
        n12 *= 2;
```

2022-11-30 00:38 UTC, EZoni commented
Note that the test `collisionXZ` is currently failing with an error of `0.0010291030859550358` vs a tolerance of `0.001`. I guess we can probably increase the tolerance slightly to, say, `0.002`, but maybe, @RemiLehe or @Yin-YinjianZhao, would you like to confirm that this is expected?

2022-11-30 18:22 UTC, RemiLehe commented
Yes, I think it is expected that the changes in this PR are affecting the test `collisionXZ`, because this test does involve intra-species collisions.

It is unclear to me, however, whether increasing the tolerance is the best course of action. We could instead update the "theoretical" predictions that we are comparing the simulation to. If I remember correctly, the "theoretical" prediction was not based on analytical theory, but was instead just a fit of the simulation results for a given version of WarpX. @Yin-YinjianZhao Could you confirm? 
If so, I think that we should update this fit - or even better: find the relevant analytical predictions.

2022-12-02 15:57 UTC, Yin-YinjianZhao commented
> Yes, I think it is expected that the changes in this PR are affecting the test `collisionXZ`, because this test does involve intra-species collisions.
> 
> It is unclear to me, however, whether increasing the tolerance is the best course of action. We could instead update the "theoretical" predictions that we are comparing the simulation to. If I remember correctly, the "theoretical" prediction was not based on analytical theory, but was instead just a fit of the simulation results for a given version of WarpX. @Yin-YinjianZhao Could you confirm? If so, I think that we should update this fit - or even better: find the relevant analytical predictions.

@RemiLehe Yes, it was based on a fit. Maybe we could follow Smeli's other tests and use the formulas they mentioned.

2022-12-02 17:22 UTC, RemiLehe commented
OK, could you send a link to that specific Smilei test?

2022-12-07 22:04 UTC, RemiLehe commented
After discussing with @Yin-YinjianZhao , the current `collisionXZ` test maybe not one of the Smilei test, but in the future, we could replace it by the first test here: https://smileipic.github.io/Smilei/Understand/collisions.html#test-cases-for-collisions since it has an analytical formula.

2023-01-04 00:59 UTC, EZoni commented on Examples/Tests/collision/analysis_collision_3d_isotropization.py
> +for i in range(nt-1):
```suggestion
for _ in range(nt-1):
```

2023-01-04 01:16 UTC, EZoni requested changes

2023-01-04 01:16 UTC, EZoni commented on Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
> +    if ( isSameSpecies ) n12 *= T_PR(2.0);
```suggestion
    if (isSameSpecies) n12 *= T_PR(2.0);
```

2023-01-04 01:16 UTC, EZoni commented on Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
> +    if ( isSameSpecies ) {
```suggestion
    if (isSameSpecies) {
```

2023-01-04 17:39 UTC, RemiLehe approved these changes

2023-01-04 17:51 UTC, EZoni approved these changes

2023-01-04 17:51 UTC, merged