Doc: remove obsolete section on reading BTD data
ECP-WarpX/WarpX pull request #3527
Opened 2022-11-15 23:14 UTC by RemiLehe

Since the only option for BTD data now is to use the regular plotfile or openPMD format, this section on the obsolete backtransformed format is no longer need.

2022-11-16 18:55 UTC, RevathiJambunathan requested changes
Thank you @RemiLehe for this PR.
Please can you also remove these files as they were added to postprocess the customized BTD output

https://github.com/ECP-WarpX/WarpX/blob/development/Tools/PostProcessing/read_lab_particles.py

https://github.com/ECP-WarpX/WarpX/blob/436934f18119543604a9c33fcb7eefcc162b4be3/Tools/PostProcessing/read_raw_data.py#L54 and this function

2022-11-16 20:41 UTC, RemiLehe commented on Tools/PostProcessing/read_raw_data.py
> -    ng = header.nghost
This was unused.

2022-11-16 20:41 UTC, RemiLehe commented on Tools/PostProcessing/read_raw_data.py
> -    ng = header.nghost
This was unused.

2022-11-16 23:12 UTC, RevathiJambunathan approved these changes
Thank you @RemiLehe

2022-11-17 02:32 UTC, EZoni approved these changes

2022-11-17 17:36 UTC, merged