Generalize Interpolation routines in diagnostics for anisotropic ref ratio
ECP-WarpX/WarpX pull request #3603
Opened 2023-01-04 19:41 UTC by prkkumar

This PR generalizes the interpolation routines in diagnostics for anisotropic refinement ratio.

2023-01-04 22:48 UTC, EZoni requested changes
Thank you for this PR, @prkkumar! It looks good to me, I left only a few suggestions.

One question:
It seems that no checksums need to be modified, does it mean that no CI test is currently using an anisotropic refinement ratio? Otherwise, I would expect some checksums  to change, if this interpolation routines are actually used for diagnostics.

2023-01-04 22:48 UTC, EZoni commented on Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
> +        //const int r_ratio = WarpX::GetInstance().refRatio(lev-1)[0];
```suggestion
```

2023-01-04 22:48 UTC, EZoni commented on Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
> +        //const int r_ratio = WarpX::GetInstance().refRatio(lev-1)[0];
```suggestion
```

2023-01-04 22:48 UTC, EZoni commented on Source/Utils/Interpolate.H
> +            const DistributionMapping& dm, const IntVect r_ratio,
```suggestion
            const DistributionMapping& dm, const amrex::IntVect r_ratio,
```

2023-01-04 22:48 UTC, EZoni commented on Source/Utils/Interpolate.H
> +            const DistributionMapping& dm, const IntVect r_ratio,
```suggestion
            const DistributionMapping& dm, const amrex::IntVect r_ratio,
```

2023-01-04 22:48 UTC, EZoni commented on Source/Utils/Interpolate.cpp
> +        const DistributionMapping& dm, const IntVect r_ratio,
```suggestion
        const DistributionMapping& dm, const amrex::IntVect r_ratio,
```

2023-01-04 22:48 UTC, EZoni commented on Source/Utils/Interpolate.cpp
> +                    IntVect refinement_vector{AMREX_D_DECL(r_ratio[0], r_ratio[1], r_ratio[2])};
```suggestion
                    amrex::IntVect refinement_vector{AMREX_D_DECL(r_ratio[0], r_ratio[1], r_ratio[2])};
```

2023-01-04 22:48 UTC, EZoni commented on Source/Utils/Interpolate.cpp
> +        const DistributionMapping& dm, const IntVect r_ratio,
```suggestion
        const DistributionMapping& dm, const amrex::IntVect r_ratio,
```

2023-01-04 22:48 UTC, EZoni commented on Source/Utils/Interpolate_K.H
> +             IntVect r_ratio, IntVect const& type) noexcept
```suggestion
             const amrex::IntVect r_ratio, IntVect const& type) noexcept
```

2023-01-04 23:09 UTC, prkkumar commented
> 

Thanks for reviewing, @EZoni! I have applied the suggestions. 

I am working on a separate PR that adds a CI test using an anisotropic refinement ratio.

2023-01-05 00:23 UTC, EZoni approved these changes

2023-01-05 00:28 UTC, atmyers approved these changes

2023-01-05 00:29 UTC, merged