[WIP] Moving window: check pointers to F,G while applying shift
ECP-WarpX/WarpX pull request #3897
Opened 2023-05-05 19:07 UTC by bensoub

2023-05-05 20:51 UTC, EZoni commented
@bensoub We need to rebase this PR since #3896 introduced a fix for the Read the Docs build that is currently failing here. We can discuss offline how to do this.

2023-05-12 17:00 UTC, EZoni requested changes

2023-05-12 17:00 UTC, EZoni commented on Source/Utils/WarpXMovingWindow.cpp
> +
```suggestion
```

2023-05-12 17:00 UTC, EZoni commented on Source/Utils/WarpXMovingWindow.cpp
> +           }
```suggestion
            }
```

2023-05-12 17:00 UTC, EZoni commented on Source/Utils/WarpXMovingWindow.cpp
> +            if (do_pml && pml[lev]->ok())
```suggestion
                // Coarse grid
                if (do_pml && pml[lev]->ok())
```

2023-05-12 17:00 UTC, EZoni commented on Source/Utils/WarpXMovingWindow.cpp
> +                // Coarse grid
```suggestion
```

2023-05-12 17:21 UTC, prkkumar approved these changes

2023-05-12 18:02 UTC, EZoni approved these changes
Thank you for your first WarpX PR, @bensoub! Looks good to me.

2023-05-12 18:04 UTC, merged