Fix issues with cupy-WarpX interoperability
ECP-WarpX/WarpX pull request #4348
Opened 2023-10-06 23:54 UTC by RemiLehe

Close #4347 

In `fields.py`, a number of GPU-relevant operation were performed based on whether or not `cupy` is installed. 
However, checking whether `cupy` is installed is not the correct logic: instead one should check e.g. whether WarpX is running on GPU, or whether the arrays that are being used are indeed `cupy` arrays. This PR tries to modify the logic accordingly.

2023-10-09 16:35 UTC, ax3l approved these changes
excellent, as discussed :+1:

2023-10-09 16:36 UTC, ax3l requested changes

2023-10-09 16:36 UTC, ax3l commented on Python/pywarpx/fields.py
> +                        slice_value = slice_value.to_numpy(copy=True)
Careful, does that work? `.to_numpy()` is only implemented in pyAMReX types. After line 
```py
slice_value = value3d[global_slices]
```
above, what do we have as type in `slice_value`?

2023-10-10 22:13 UTC, RemiLehe commented
@EyaDammak confirmed that this works as expected in practice, both for GPU and CPU runs.

2023-10-10 23:29 UTC, ax3l approved these changes

2023-10-10 23:31 UTC, merged