[WIP] Exchange guard cells for electrostatic solver
ECP-WarpX/WarpX pull request #4713
Opened 2024-02-21 17:20 UTC by RemiLehe

2024-02-22 23:13 UTC, RemiLehe commented on Examples/Tests/energy_conserving_thermal_plasma/analysis.py
> +import yt
```suggestion
```

2024-02-23 14:50 UTC, RemiLehe commented on Regression/WarpX-tests.ini
> +inputFile = Examples/Tests/Implicit/inputs_2d_electrostatic
```suggestion
inputFile = Examples/Tests/energy_conserving_thermal_plasma/inputs_2d_electrostatic
```

2024-02-24 04:06 UTC, lucafedeli88 requested changes
Thanks for this PR! I left few minor comments

2024-02-24 04:06 UTC, lucafedeli88 commented on Examples/Tests/energy_conserving_thermal_plasma/inputs_2d_electrostatic
> +my_constants.n0 = 1.e30          # plasma densirty, m^-3
```suggestion
my_constants.n0 = 1.e30          # plasma density, m^-3
```
just a typo

2024-02-24 04:06 UTC, lucafedeli88 commented on Examples/Tests/energy_conserving_thermal_plasma/inputs_2d_electrostatic
> +boundary.field_hi = periodic periodic
```suggestion

#################################
###### BOUNDARY CONDITIONS ######
#################################
boundary.field_lo = periodic periodic
boundary.field_hi = periodic periodic
boundary.particle_lo = periodic periodic
boundary.particle_hi = periodic periodic
```

The same conditions are repeated twice.

2024-02-24 04:06 UTC, lucafedeli88 commented on Examples/Tests/energy_conserving_thermal_plasma/inputs_2d_electrostatic
> +warpx.verbose = 1
I think that these parameters could be considered "general parameters" rather then "numerics" (they are not technical parameters of the solvers used in WarpX)

2024-02-24 04:06 UTC, lucafedeli88 commented on Examples/Tests/energy_conserving_thermal_plasma/inputs_2d_electrostatic
> +warpx.use_filter = 0
I think that these parameters should be under "numerics"

2024-02-24 04:06 UTC, lucafedeli88 commented on Examples/Tests/energy_conserving_thermal_plasma/inputs_2d_electrostatic
> +geometry.prob_hi = 10.*de0 10.*de0
These parameters could be placed in the "general parameters" section above.

2024-02-27 16:59 UTC, dpgrote approved these changes
Thanks! This looks good.

2024-02-27 18:46 UTC, merged