Adding hyper-resistivity to generalized ohms law hybrid solver.
ECP-WarpX/WarpX pull request #4772
Opened 2024-03-13 18:05 UTC by clarkse

Hyper resistivity is added to the generalized Ohm's law solver to suppress spurious whistler noise in low density regions.  This required addition of Laplacian operators to evaluate the extra term in the Ohm's law.  (\nabla^2 J)

2024-03-13 23:00 UTC, roelof-groenewald requested changes
Looks good! Thanks for the enhancement!
I just left a few minor comments for consistency, and I think it would be good to not add the `include_hyper_resistivity_term` argument since it can be inferred inside the `HybridPICSolveE` function.

2024-03-13 23:00 UTC, roelof-groenewald commented on Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianYeeAlgorithm.H
> +            i, j, k, ncomp);
Since the cases above cover all options this can be removed.
```suggestion
```

2024-03-13 23:00 UTC, roelof-groenewald commented on Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
> +    HybridPICSolveE(Efield, Jfield, Bfield, rhofield, edge_lengths, true, do_hyper_resisitivity);
Seeing as the `do_hyper_resistivity` flag is essentially
```
do_hyper_resistivity = (m_eta_h > 0.0) && include_resistivity_term
```
we don't need an extra function argument for it, but can instead evaluate the above expression inside `HybridPICSolveE`.

2024-03-13 23:00 UTC, roelof-groenewald commented on Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CylindricalYeeAlgorithm.H
> +        amrex::Real const * const coefs_r, int const n_coefs_r,
For consistency with `Dzz`:
```suggestion
        amrex::Real const * const coefs_r, int const /*n_coefs_r*/,
```

2024-03-13 23:00 UTC, roelof-groenewald commented on Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CylindricalYeeAlgorithm.H
> +        ignore_unused(n_coefs_r);
```suggestion
```

2024-03-13 23:00 UTC, roelof-groenewald commented on Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianYeeAlgorithm.H
> +        amrex::Real const * const coefs_y, int const n_coefs_y,
For consistency with `Dxx`:
```suggestion
        amrex::Real const * const coefs_y, int const /*n_coefs_y*/,
```

2024-03-13 23:00 UTC, roelof-groenewald commented on Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianYeeAlgorithm.H
> +        amrex::ignore_unused(n_coefs_y);
```suggestion
```

2024-03-13 23:00 UTC, roelof-groenewald commented on Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianYeeAlgorithm.H
> +            i, j, k, ncomp);
```suggestion
        amrex::ignore_unused(F, coefs_y, i, j, k, ncomp);
```

2024-03-13 23:21 UTC, clarkse commented on Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
> +    HybridPICSolveE(Efield, Jfield, Bfield, rhofield, edge_lengths, true, do_hyper_resisitivity);
Sounds reasonable to me.  I can go through and update the function prototypes to drop the argument.

2024-03-14 04:48 UTC, roelof-groenewald approved these changes
Thanks so much for the addition!

2024-03-14 04:48 UTC, merged