Updated visualization scripts for beam-beam collision example
ECP-WarpX/WarpX pull request #4797
Opened 2024-03-21 23:33 UTC by Haavaan

We have presented here the modified full and reduced beam-beam collision diagnostics that also includes the python scripts. In the full diagnostics, we have simulated the evolution of the E, B, and Rho fields across the x and y slices. While in the reduced diagnostics, we have simulated the evolution of the number of photons emitted per beam particle and the number of secondary pairs generated per beam particle produced when two ultra-relativistic particle beams collide in a linear collider.

2024-04-17 21:09 UTC, aeriforme requested changes

2024-04-17 21:09 UTC, aeriforme commented on Examples/Physics_applications/beam-beam_collision/plot_reduced.py
> +from matplotlib import cm, use
@Haavaan could you remove the unused imports?

2024-04-17 21:09 UTC, aeriforme commented on Examples/Physics_applications/beam-beam_collision/plot_reduced.py
> +)
same as above

2024-04-17 21:09 UTC, aeriforme commented on Examples/Physics_applications/beam-beam_collision/README.rst
I know this you didn't modify this portion of the file, but we might as well just fix it. 
Can you change line 14

`This solver computes the average velocity of each species, and solves the corresponding relativistic Poisson equation (see the WarpX documentation for `warpx.do_electrostatic = relativistic` for more detail). This solver accurately reproduced the subtle cancellation that occur for some component of the ``E + v x B`` terms which are crucial in simulations of relativistic particles.`

to 

`This solver computes the average velocity of each species, and solves the corresponding relativistic Poisson equation (see the WarpX documentation for ``warpx.do_electrostatic = relativistic`` for more details). This solver accurately reproduces the subtle cancellation that occurs for some components of ``E + v x B``, which is crucial in simulations of relativistic particles.`

2024-04-17 21:09 UTC, aeriforme commented on Examples/Physics_applications/beam-beam_collision/README.rst
> +
Can you add here a brief description of the visualization scripts?
Also, it would be nice to add an image from the full diagnostics to show what the script is supposed to produce.

2024-04-17 21:09 UTC, aeriforme commented on Examples/Physics_applications/beam-beam_collision/README.rst
> +    from openpmd_viewer import OpenPMDTimeSeries
Fix the indentation from here on, otherwise it's not recognized as part of the code block.

2024-04-17 21:09 UTC, aeriforme commented on Examples/Physics_applications/beam-beam_collision/README.rst
> +    import numpy as np
Same indentation issue here.

2024-08-19 20:24 UTC, aeriforme approved these changes

2024-09-16 23:45 UTC, aeriforme reviewed
I made some changes here https://github.com/Haavaan/WarpX/pull/9
but I don't have the rights to push them.

2024-09-17 18:05 UTC, RemiLehe approved these changes

2024-09-17 19:12 UTC, merged