Docs: Thomson Parabola Spectrometer example
ECP-WarpX/WarpX pull request #5058
Opened 2024-07-18 01:24 UTC by aeriforme

This PR adds a new example where different ion species travel through a Thomson Parabola Spectrometer and are collected at a screen. 
The example can be found in the `PhysicsApplications/thomson_parabola_spectrometer` folder.

2024-07-18 08:43 UTC, lucafedeli88 requested changes
Hi @aeriforme ! Thanks a lot for this PR! I've left a couple of comments.
In addition we should consider (and I don't have an immediate answer):
- where should we store the figures (our current policy forbids files that are not inputfiles, scripts or README in the example folder)
- if this example should also become a CI test

2024-07-18 08:43 UTC, lucafedeli88 commented on Examples/Physics_applications/thomson_parabola_spectrometer/README.rst
> + - a vacuum region, the distance between the TPS and the screen of the detector (0.2 m)
```suggestion
 * a vacuum region, the distance between the pinhole and the TPS (0.1 m)
 * a region of constant electric field along :math:`x`, (0.19 m, 1e5 V/m)
 * a region of constant magnetic field along :math:`x`, (0.872 T, 0.12 m)
 * a vacuum region, the distance between the TPS and the screen of the detector (0.2 m)
```

I think that `*` is required for a bullet list.

2024-07-18 08:43 UTC, lucafedeli88 commented on Examples/Physics_applications/thomson_parabola_spectrometer/plot_detector.py
> +Emax_carbon12_5 = 20*MeV
In your example you seem to have only H1 and C6, however in the script and in the figure you also have C5. This might be a bit confusing for the user

2024-07-18 23:32 UTC, aeriforme commented on Examples/Physics_applications/thomson_parabola_spectrometer/plot_detector.py
> +Emax_carbon12_5 = 20*MeV
ooops, wrong inputfile, let me fix it

2024-07-18 23:33 UTC, aeriforme commented on Examples/Physics_applications/thomson_parabola_spectrometer/README.rst
> + - a vacuum region, the distance between the TPS and the screen of the detector (0.2 m)
I think it works with `-` too, I have compiled it and checked

2024-07-31 09:23 UTC, lucafedeli88 commented on Examples/Physics_applications/thomson_parabola_spectrometer/README.rst
> + - a vacuum region, the distance between the TPS and the screen of the detector (0.2 m)
Yes, you are right! Sorry.

2024-07-31 11:18 UTC, lucafedeli88 requested changes
Thanks a lot for this new example, @aeriforme .

I left very few comments, but I think that this PR could be merged very soon.

2024-07-31 11:18 UTC, lucafedeli88 commented on Examples/Physics_applications/thomson_parabola_spectrometer/analysis.py
> +Emax_carbon12_5 = 20*MeV
```suggestion
Emax_carbon12_4 = 20*MeV
```
Shouldn't this be `Emax_carbon12_4` ?

2024-07-31 11:18 UTC, lucafedeli88 commented on Examples/Physics_applications/thomson_parabola_spectrometer/analysis.py
> +Emax_carbon12_5 = 20*MeV
But in any case it seems that these variables are unused. Maybe you can comment them or delete them

2024-07-31 11:18 UTC, lucafedeli88 commented on Regression/WarpX-tests.ini
> +runtime_params = warpx.abort_on_warning_threshold=high
```suggestion
runtime_params = warpx.abort_on_warning_threshold=low
```

The test does not seem to raise any warning at the moment. We can lower the threshold to abort to `low`, I think.

2024-07-31 11:18 UTC, lucafedeli88 commented on Examples/Physics_applications/thomson_parabola_spectrometer/inputs
> +diag1.dump_last_timestep = 1
`diag1` plots the simulation results also at timestep 0, which is what `diag0` does. Is this the intended behavior?

2024-08-27 12:12 UTC, lucafedeli88 requested changes
Hi @aeriforme ! I have only one tiny comment. Besides of this comment, the PR looks very good.

2024-08-27 12:12 UTC, lucafedeli88 commented on Examples/Physics_applications/thomson_parabola_spectrometer/inputs
> +diag1.intervals = 0
Do you mean at time zero (`0:0` would be preferable, I think) or "at every timestep" (in which case I would suggest `1`)?

2024-09-17 09:23 UTC, lucafedeli88 commented
@aeriforme , could you please fix the merge conflicts?

2024-10-30 01:10 UTC, lucafedeli88 approved these changes
Great PR,  @aeriforme .
I left a comment because it seems to me that some comment lines in the inputfile got mixed up, but otherwise it looks good to me

2024-10-30 01:10 UTC, lucafedeli88 commented on Examples/Physics_applications/thomson_parabola_spectrometer/inputs_test_3d_thomson_parabola_spectrometer
> +# uniform energy distribution in [0.5*Emax,Emax]
There seems to be something wrong with this comment.

2024-11-15 16:23 UTC, merged