[WIP] PSATD-JRom with an arbitrary temporal dependency of `J` and `rho`.
ECP-WarpX/WarpX pull request #5088
Opened 2024-07-26 23:06 UTC by oshapoval

[WIP]  This PR replaces https://github.com/ECP-WarpX/WarpX/pull/4263.

2024-07-29 17:08 UTC, EZoni commented on Regression/Checksum/benchmarks_json/uniform_plasma_psatd_CC2.json
This file is empty and I think `pre-commit` doesn't like it. Is it an obsolete file that we can remove or do we need to add checksum values here?

2024-07-29 17:13 UTC, EZoni requested changes

2024-07-29 17:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +particleTypes = electrons positrons
It should be safe to remove these parameters as they are unused, see #5043:
```suggestion
```

2024-07-29 17:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +particleTypes = electrons positrons
It should be safe to remove these parameters as they are unused, see #5043:
```suggestion
```

2024-07-29 17:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +particleTypes = electrons positrons
It should be safe to remove these parameters as they are unused, see #5043:
```suggestion
```

2024-07-29 17:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +particleTypes = electrons positrons
It should be safe to remove these parameters as they are unused, see #5043:
```suggestion
```

2024-07-29 17:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +particleTypes = electrons positrons
It should be safe to remove these parameters as they are unused, see #5043:
```suggestion
```

2024-07-29 17:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +particleTypes = electrons ions
It should be safe to remove these parameters as they are unused, see #5043:
```suggestion
```

2024-07-29 17:21 UTC, EZoni commented on Regression/WarpX-tests.ini
Maybe we could add `JRhom` in the name of each new test, too. Something like `Langmuir_multi_2d_psatd_JRhom_LL2_first_order`, etc., or something along these lines. So that it's clear to everyone that these tests are related to the `JRhom` options.

2024-07-29 17:53 UTC, EZoni commented on Regression/WarpX-tests.ini
If #5097 shows that `analysisOutputImage` is indeed an obsolete, unused parameter, we will remove it from the new tests here as well.

2024-07-30 00:13 UTC, EZoni requested changes

2024-07-30 00:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_2d_psatd_LL2_first_order.png
See https://github.com/ECP-WarpX/WarpX/pull/5088/files#r1695643012:
```suggestion
```

2024-07-30 00:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_2d_psatd_LL2_first_order_nodal.png
See https://github.com/ECP-WarpX/WarpX/pull/5088/files#r1695643012:
```suggestion
```

2024-07-30 00:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_2d_psatd_CC2_nodal.png
See https://github.com/ECP-WarpX/WarpX/pull/5088/files#r1695643012:
```suggestion
```

2024-07-30 00:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_2d_psatd_LL1_nodal.png
See https://github.com/ECP-WarpX/WarpX/pull/5088/files#r1695643012:
```suggestion
```

2024-07-30 00:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_2d_psatd_QQ1_nodal.png
See https://github.com/ECP-WarpX/WarpX/pull/5088/files#r1695643012:
```suggestion
```

2024-07-30 00:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_2d_psatd_LQ1_nodal.png
See https://github.com/ECP-WarpX/WarpX/pull/5088/files#r1695643012:
```suggestion
```

2024-07-30 00:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_2d_psatd_LL1.png
See https://github.com/ECP-WarpX/WarpX/pull/5088/files#r1695643012:
```suggestion
```

2024-07-30 00:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_psatd_LL2_first_order.png
See https://github.com/ECP-WarpX/WarpX/pull/5088/files#r1695643012:
```suggestion
```

2024-07-30 00:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_psatd_LL2_first_order_nodal.png
See https://github.com/ECP-WarpX/WarpX/pull/5088/files#r1695643012:
```suggestion
```

2024-07-30 00:13 UTC, EZoni commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_rz_psatd_LL4_analysis.png
See https://github.com/ECP-WarpX/WarpX/pull/5088/files#r1695643012:
```suggestion
```

2024-07-30 00:50 UTC, oshapoval commented on Regression/WarpX-tests.ini
Sounds good to me. One might also explicitly add to the Documentation section that standard PSATD is equivalent to `psatd_JRhom_CL1`.

2025-02-19 20:44 UTC, oshapoval commented on Regression/WarpX-tests.ini
> +particleTypes = electrons positrons
Resolved on its own since `Regression/WarpX-tests.ini` has been removed.

2025-02-19 20:44 UTC, oshapoval commented on Regression/WarpX-tests.ini
> +particleTypes = electrons positrons
Resolved on its own since Regression/WarpX-tests.ini has been removed.

2025-02-19 20:46 UTC, oshapoval commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_2d_psatd_LL2_first_order.png
`Regression/WarpX-tests.ini` has been removed.

2025-02-19 20:46 UTC, oshapoval commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_2d_psatd_CC2_nodal.png
`Regression/WarpX-tests.ini` has been removed

2025-02-19 20:47 UTC, oshapoval commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_2d_psatd_QQ1_nodal.png
`Regression/WarpX-tests.ini` has been removed.

2025-02-19 20:47 UTC, oshapoval commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_psatd_LL2_first_order.png
`Regression/WarpX-tests.ini` has been removed.

2025-02-19 20:47 UTC, oshapoval commented on Regression/WarpX-tests.ini
> +analysisOutputImage = Langmuir_multi_rz_psatd_LL4_analysis.png
`Regression/WarpX-tests.ini` has been removed.

2025-04-05 00:41 UTC, EZoni commented
Replaced by #5682.

2025-04-05 00:41 UTC, closed without merging

2025-04-05 00:41 UTC, EZoni commented
Replaced by #5682.