Add ionization documentation
ECP-WarpX/WarpX pull request #5251
Opened 2024-09-11 17:40 UTC by n01r

This PR adds documentation for the existing ionization model in WarpX.
It follows the structure of #5245.

2024-09-12 21:48 UTC, roelof-groenewald requested changes

2024-09-12 21:48 UTC, roelof-groenewald commented on Docs/source/theory/multiphysics/ionization.rst
> +--------
I think we should move this section to Examples and just put a link here. In that case the details described here can go in a README file in `Examples/Tests/ionization/`.

2024-09-13 17:10 UTC, n01r commented
@roelof-groenewald, the test docs are now moved to the test directory. :)

In a future PR we could split the section in the docs to reflect the repository structure:

```
Usage 
     \__ Examples
                 \__ Physical Applications
                 \__ Tests
```

We could repack the commits into fewer ones and have to make sure that @johvandewetering really gets credited, too. That seems to have been lost a bit on the rebase.

2024-09-13 19:03 UTC, roelof-groenewald approved these changes
Thanks for the updates!

2024-09-13 20:30 UTC, merged