Add reduced_diags general input
ECP-WarpX/WarpX pull request #5479
Opened 2024-11-21 21:44 UTC by dpgrote

This PR adds the `reduced_diags` input parameter group that allows setting of parameters common to all reduced diagnostics. For example 'reduced_diags.intervals` can be set once rather than having to set it for each individual reduced diagnostic.

2024-11-22 01:13 UTC, EZoni commented on .github/workflows/clang_sanitizers.yml
Unfortunately, I think `ubuntu-23.10` is not an available runner: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories. This might explain why the CI jobs are not starting.

I'm trying to remove the container and use `ubuntu-24.04` in #5474, but I'm finding new bugs that I haven't been able to fix yet.

2024-12-04 00:13 UTC, roelof-groenewald requested changes
Thanks! These are helpful updates. In a follow-up PR we can also extend the `picmi` inputs to make use of this.
Once the `clang_sanitizers.yml` changes have been reverted we can merge.

2024-12-04 00:13 UTC, roelof-groenewald commented on .github/workflows/clang_sanitizers.yml
@dpgrote I guess the changes to this file can be reverted now that the sanitizer tests have been fixed / disabled.

2024-12-04 17:04 UTC, dpgrote commented on .github/workflows/clang_sanitizers.yml
Good point about adding this to picmi. So it doesn't get forgotten, I'll add it to this PR. And I'll undo the change in the workflows script.

2024-12-04 17:32 UTC, dpgrote commented on .github/workflows/clang_sanitizers.yml
Though, looking at the picmi interface, this doesn't really apply there since each diagnostic is setup separately. There isn't a clear way to set a parameter for all reduced diagnostics. Do you have any suggestions?

2024-12-04 17:40 UTC, roelof-groenewald commented on .github/workflows/clang_sanitizers.yml
One option would be to add an argument to `Simulation` that sets a global diagnostic period (and output directory, etc.). These parameters could then be passed to along to `diagnostic_initialize_inputs()` to be used if the individual diagnostic did not have a value set. It will require changing some defaults, since currently the default period for reduced diagnostics is `1`, but I guess we'd have to change it to `None` in order to check if a value was set.

2024-12-04 18:00 UTC, dpgrote commented on .github/workflows/clang_sanitizers.yml
Ok, that could work. It can be a bit simpler too since Simulation could directly set the parameters, e.g. `reduced_diags.intervals`.

BTW, the default for the period in ReducedDiagnostic should be None anyway so that it doesn't override the default set in C++.

2024-12-04 19:44 UTC, roelof-groenewald approved these changes

2024-12-04 19:44 UTC, roelof-groenewald commented on Python/pywarpx/picmi.py
> +        reduced_diags.precision = self.reduced_diags_precision
Nice! This is even cleaner than my original suggestion 🎉

2024-12-04 21:08 UTC, merged